@startuml Proposal state

title Proposal state transition diagram

hide empty description

state "Proposal Phase" as ProposalPhase {
    [*] --> Created : propose()

    Created -> Canceled : cancel(id)
    Canceled -> [*]
}

note left of ProposalPhase
    **14 days duration period**
    New proposals can be сreated
    or canceled.
end note

state "Voting Phase" as VotingPhase {
    Created --> Active : switchPhase()

    Active --> Active : collecting votes
}

note left of VotingPhase
    **14 days duration period**
    Voting on existing proposals.
    New proposals cannot be created.
end note

Active --> VotingFinished : switchPhase()

state ProposalFinalized <<choice>>

VotingFinished --> ProposalFinalized : finalize(id)

ProposalFinalized -> Declined : [2/3 acceptance not reached]
Declined -> [*]

ProposalFinalized --> Accepted : [2/3 acceptance reached]
Accepted -> Executed : execute(id)
Executed -> [*]


@enduml
