name: Build & test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.18.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.x.x
          cache: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm hardhat build

      - name: Run tests with coverage
        run: pnpm hardhat test --coverage

      - name: Grype vulnerability scan
        uses: anchore/scan-action@v7
        id: grype-scan
        with:
          path: "."
          config: .grype.yaml
        env:
          SYFT_SOURCE_NAME: diamond-contracts-dao
          SYFT_SOURCE_VERSION: ${{ github.sha }}

      - name: Grype scan report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.grype-scan.outputs.sarif }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
